# To build this project, run these commands:
# Build the Debug version
mkdir -p build-debug && cd build-debug && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=EFR32BG1.cmake .. && make
cd ..
#
# Build the release version
mkdir -p build-release && cd build-release && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=EFR32BG1.cmake .. && make
