/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define GATTDB_service_changed_char             3
#define GATTDB_serialnum                       16
#define GATTDB_hwrev                           18
#define GATTDB_fwrev                           20
#define GATTDB_ota_control                     23
#define GATTDB_ota_data                        26

#endif
